# Generated by Django 4.2.6 on 2024-03-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Created'), (2, 'Paid'), (3, 'On way'), (4, 'Delivered'), (0, 'Canceled')], default=1),
        ),
    ]
