# Generated by Django 4.2.6 on 2023-11-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products_images/default_image.jpg', upload_to='products_images'),
        ),
    ]
