# Generated by Django 4.2.6 on 2023-11-08 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productspecs',
            options={'verbose_name': 'ProductSpecs', 'verbose_name_plural': 'ProductSpecs'},
        ),
    ]
