# Generated by Django 4.2.6 on 2023-11-08 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productreview_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productspecs',
            unique_together={('name', 'product_id')},
        ),
    ]
