# Generated by Django 5.0 on 2023-12-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubcategory',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='description_uk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='name_en',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='name_uk',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
