# Generated by Django 4.2.6 on 2023-12-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_description_en_product_description_uk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='description_uk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_en',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_uk',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productspecs',
            name='name_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='productspecs',
            name='name_uk',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='productspecs',
            name='value_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='productspecs',
            name='value_uk',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
