# Generated by Django 4.2.6 on 2024-03-20 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_product_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcategorySpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256)),
                ('allowed_value', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='category_idx',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='subcategory',
        ),
        migrations.AlterField(
            model_name='productspecs',
            name='name',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='productspecs',
            name='name_en',
            field=models.CharField(db_index=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='productspecs',
            name='name_uk',
            field=models.CharField(db_index=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='productspecs',
            name='value',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='productspecs',
            name='value_en',
            field=models.CharField(db_index=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='productspecs',
            name='value_uk',
            field=models.CharField(db_index=True, max_length=256, null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['subcategory'], name='subcategory_idx'),
        ),
        migrations.AddField(
            model_name='subcategoryspecs',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productsubcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='subcategoryspecs',
            unique_together={('name', 'subcategory')},
        ),
    ]
